GET http://localhost:8080/CA1_projekt_war_exploded/api/persons

###
GET http://localhost:8080/CA1_projekt_war_exploded/api/hobbies

###
POST https://christoffermikkelsen.dk/CA-1_projekt/api/persons
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "First Property"}

###
PUT http://localhost:8080/devops_starter_war_exploded/api/xxx